name: Auto commit

on:
  push:
    branches:
      - main
  workflow_dispatch:
  
  schedule:
    - cron: "0 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20 * * *" # See https://crontab.guru/#0_7,9,11,17,20_*_*_*

jobs:
  auto_commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Wajib ada supaya bot bisa nge-push balik ke repo

    steps:
      - uses: actions/checkout@v3 # Gunakan v3 atau v4 yg lebih baru
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Modify last update & Commit
        run: |
          # Config git user
          git config --global --add safe.directory /github/workspace
          git config --local user.email "ahmadnawfal2003@gmail.com"
          git config --local user.name "ahmdnawfal"

          # Loop sebanyak 5 kali (atau random range)
          MAX_LOOP=5
          
          for (( i=1; i<=MAX_LOOP; i++ ))
          do
            d=$(date '+%Y-%m-%dT%H:%M:%SZ')
            echo "Last Update: $d - Iteration $i" > LAST_UPDATED
            
            git add -A
            
            arr=("chore(bot): ğŸ˜‚ auto commit" "chore(bot): ğŸ˜± auto commit" "chore(bot): ğŸ‘¿ auto commit" "chore(bot): ğŸ’© auto commit" "chore(bot): ğŸ™ auto commit" "chore(bot): ğŸ™ˆ auto commit" "chore(bot): ğŸ auto commit" "chore(bot): ğŸ¤– auto commit" "chore(bot): ğŸŸ© auto commit" "chore(bot): ğŸ‘» auto commit")
            rand=$[$RANDOM % ${#arr[@]}]
            
            git commit -m "${arr[$rand]}"
            
            # Kasih delay dikit biar timestamp commit beda detik
            sleep 1
          done

      - name: GitHub Push
        uses: ad-m/github-push-action@v0.6.0
        with:
          force: true
          directory: "."
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
